In [ ]:
import pandas

In [3]:
data=pandas.read_csv(r"D:\Classes\Python\House Price Prediction Project\Data\Housing.csv")
data

price  area  bedrooms  bathrooms mainroad guestroom hotwaterheating  \
0    13300000  7420         4          2      yes        no              no   
1    12250000  8960         4          4      yes        no              no   
2    12250000  9960         3          2      yes        no              no   
3    12215000  7500         4          2      yes        no              no   
4    11410000  7420         4          1      yes       yes              no   
..        ...   ...       ...        ...      ...       ...             ...   
540   1820000  3000         2          1      yes        no              no   
541   1767150  2400         3          1       no        no              no   
542   1750000  3620         2          1      yes        no              no   
543   1750000  2910         3          1       no        no              no   
544   1750000  3850         3          1      yes        no              no   

    airconditioning  parking prefarea  
0               yes        2      yes  
1               yes        3       no  
2                no        2      yes  
3               yes        3      yes  
4               yes        2       no  
..              ...      ...      ...  
540              no        2       no  
541              no        0       no  
542              no        0       no  
543              no        0       no  
544              no        0       no  

[545 rows x 10 columns]

In [4]:
len(data)

545

In [ ]:
data.columns

In [5]:
for i in ["mainroad","guestroom","hotwaterheating","airconditioning","prefarea"]:
    data[i]=data[i].map({"yes":1,"no":0})

In [6]:
data

price  area  bedrooms  bathrooms  mainroad  guestroom  \
0    13300000  7420         4          2         1          0   
1    12250000  8960         4          4         1          0   
2    12250000  9960         3          2         1          0   
3    12215000  7500         4          2         1          0   
4    11410000  7420         4          1         1          1   
..        ...   ...       ...        ...       ...        ...   
540   1820000  3000         2          1         1          0   
541   1767150  2400         3          1         0          0   
542   1750000  3620         2          1         1          0   
543   1750000  2910         3          1         0          0   
544   1750000  3850         3          1         1          0   

     hotwaterheating  airconditioning  parking  prefarea  
0                  0                1        2         1  
1                  0                1        3         0  
2                  0                0        2         1  
3                  0                1        3         1  
4                  0                1        2         0  
..               ...              ...      ...       ...  
540                0                0        2         0  
541                0                0        0         0  
542                0                0        0         0  
543                0                0        0         0  
544                0                0        0         0  

[545 rows x 10 columns]

In [7]:
#Import Machine learning libraries
from sklearn import linear_model
from sklearn.model_selection import train_test_split
mymodel=linear_model.LinearRegression()

In [9]:
# Mapping Dataset to X and Y
X=data[["area","bedrooms","bathrooms","mainroad","guestroom","hotwaterheating","airconditioning","parking","prefarea"]]
y=data["price"]

In [12]:
len(y)

545

In [13]:
XTrain,XTest,YTrain,YTest=train_test_split(X,y,random_state=10,test_size=0.3)

In [15]:
len(XTest)

164

In [ ]:
print(XTrain.info())

In [16]:
#Training Model
mymodel.fit(XTrain,YTrain)

LinearRegression()

In [17]:
#["area","bedrooms","bathrooms","mainroad","guestroom","hotwaterheating","airconditioning","parking","prefarea"]
mymodel.predict([[5000,3,2,1,0,0,1,2,1]])

c:\Users\Rakesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([7283013.14313226])

In [18]:
ypred=mymodel.predict(XTest)

In [19]:
ypred

array([ 2629246.02571414,  3418840.5124162 ,  5576480.02467987,
        4201522.51875052,  5936226.69741119,  6580009.90300652,
        4004419.5630373 ,  3029372.85837688,  5004312.69235562,
        3551997.37928873,  5423671.63662309,  2371206.85627997,
        3815906.87660812,  4709366.04310832,  6723178.83166796,
        2424777.72754486,  7393801.4377797 ,  6295515.1222583 ,
        4994472.67414473,  4453345.18966245,  3028306.92435963,
        2197329.29779316,  5437763.43080846,  5739245.72869366,
        6876347.86221828,  6469392.68074511,  4018247.89130032,
        3683045.86873065,  3917614.37990528,  3484206.76379603,
        3847084.92157817,  4597463.69200244,  5387292.4291861 ,
        4872362.93886246,  7120785.09614869,  4712470.48310973,
        6783988.3378833 ,  2146964.76361078,  5255025.80161476,
        6012153.49384802,  4901230.93523169,  4643663.49806107,
        3107671.9130039 ,  7082337.26569233,  6333374.98404249,
        6952545.91034089,  9178855.51846

In [20]:
from sklearn.metrics import r2_score
import numpy
r2_score(numpy.array(YTest),numpy.array(ypred))

0.7004321757859057

In [21]:
import pickle
pickle.dump(mymodel,open("Model.sav","wb"))

In [22]:
import pickle
model=pickle.load(open("Model.sav","rb"))

In [23]:
model.predict([[9000,3,2,1,0,0,1,2,1]])

c:\Users\Rakesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([8242337.60374913])